import 'package:stradmon_chairs/constants/app_images.dart';
import 'package:stradmon_chairs/model/shirt.dart';

List<Shirt> shirts = [
  Shirt(
    id: 1,
    name: 'Jeans Shirt',
    intensity: 9,
    shirtType: 'Shirt',
    price: 775,
    isActive: true,
    bestSellers: true,
    imageAssets: AppImages.jeansShirt,
    description:
        'A shirt is a versatile garment worn on the upper body, typically with sleeves, a collar, and buttons down the front. It comes in various styles, fabrics, and colors, making it a fundamental element of contemporary fashion. Shirts can be formal or casual, suitable for different occasions and settings. ',
    rating: 9.5,
  ),
  Shirt(
    id: 2,
    name: 'Violet Shirt',
    intensity: 3,
    shirtType: 'Shirt',
    price: 450,
    isActive: true,
    bestSellers: true,
    imageAssets: AppImages.violetShirt,
    description:
        'A shirt is a versatile garment worn on the upper body, typically with sleeves, a collar, and buttons down the front. It comes in various styles, fabrics, and colors, making it a fundamental element of contemporary fashion. Shirts can be formal or casual, suitable for different occasions and settings. .',
    rating: 9.5,
  ),
  Shirt(
    id: 3,
    name: 'Long Sleeve Shirt',
    intensity: 8,
    shirtType: 'Shirt',
    price: 550,
    isActive: true,
    bestSellers: true,
    imageAssets: AppImages.blackLongSleeve,
    description:
        'A shirt is a versatile garment worn on the upper body, typically with sleeves, a collar, and buttons down the front. It comes in various styles, fabrics, and colors, making it a fundamental element of contemporary fashion. Shirts can be formal or casual, suitable for different occasions and settings. ',
    rating: 7.5,
  ),
  Shirt(
    id: 4,
    name: 'Red Lacoste',
    intensity: 4,
    shirtType: 'Lacoste',
    price: 620,
    isActive: true,
    bestSellers: false,
    imageAssets: AppImages.redLacoste,
    description:
        'A shirt is a versatile garment worn on the upper body, typically with sleeves, a collar, and buttons down the front. It comes in various styles, fabrics, and colors, making it a fundamental element of contemporary fashion. Shirts can be formal or casual, suitable for different occasions and settings. ',
    rating: 7.4,
  ),
  Shirt(
    id: 5,
    name: 'Blue Shirt',
    intensity: 7,
    shirtType: 'Lacoste',
    price: 401,
    isActive: true,
    bestSellers: false,
    imageAssets: AppImages.blueShirt,
    description:
        'A shirt is a versatile garment worn on the upper body, typically with sleeves, a collar, and buttons down the front. It comes in various styles, fabrics, and colors, making it a fundamental element of contemporary fashion. Shirts can be formal or casual, suitable for different occasions and settings. ',
    rating: 7.2,
  ),
  Shirt(
    id: 6,
    name: 'Deep Blue Shirt',
    intensity: 4,
    shirtType: 'Lacoste',
    price: 460,
    isActive: true,
    bestSellers: true,
    imageAssets: AppImages.deepBlueShirt,
    description:
        'A shirt is a versatile garment worn on the upper body, typically with sleeves, a collar, and buttons down the front. It comes in various styles, fabrics, and colors, making it a fundamental element of contemporary fashion. Shirts can be formal or casual, suitable for different occasions and settings. ',
    rating: 8.9,
  ),
  Shirt(
    id: 7,
    name: 'Red Shirt',
    intensity: 3,
    shirtType: 'Long',
    price: 575,
    isActive: true,
    bestSellers: true,
    imageAssets: AppImages.redShirt,
    description:
        'A shirt is a versatile garment worn on the upper body, typically with sleeves, a collar, and buttons down the front. It comes in various styles, fabrics, and colors, making it a fundamental element of contemporary fashion. Shirts can be formal or casual, suitable for different occasions and settings. . ',
    rating: 8.6,
  ),
  Shirt(
    id: 8,
    name: 'Green Shirt',
    intensity: 6,
    shirtType: 'Long',
    price: 390,
    isActive: true,
    bestSellers: false,
    imageAssets: AppImages.greenShirt,
    description:
        'A shirt is a versatile garment worn on the upper body, typically with sleeves, a collar, and buttons down the front. It comes in various styles, fabrics, and colors, making it a fundamental element of contemporary fashion. Shirts can be formal or casual, suitable for different occasions and settings. .',
    rating: 8.4,
  ),
  Shirt(
    id: 9,
    name: 'New Shirt',
    intensity: 3,
    shirtType: 'Long',
    price: 590,
    isActive: true,
    bestSellers: false,
    imageAssets: AppImages.whiteLongSleeve,
    description:
        'A shirt is a versatile garment worn on the upper body, typically with sleeves, a collar, and buttons down the front. It comes in various styles, fabrics, and colors, making it a fundamental element of contemporary fashion. Shirts can be formal or casual, suitable for different occasions and settings. .',
    rating: 6.5,
  ),
  Shirt(
    id: 10,
    name: 'Orange Shirt',
    intensity: 3,
    shirtType: 'Trousers',
    price: 602,
    isActive: true,
    bestSellers: false,
    imageAssets: AppImages.orangeShirt,
    description:
        'A shirt is a versatile garment worn on the upper body, typically with sleeves, a collar, and buttons down the front. It comes in various styles, fabrics, and colors, making it a fundamental element of contemporary fashion. Shirts can be formal or casual, suitable for different occasions and settings. .',
    rating: 9.1,
  ),
];
